using System;
using System.Drawing;
using System.Runtime.InteropServices;
using Foundation;
using UIKit;

// Generated by Objective Sharpie (https://download.xamarin.com/objective-sharpie/ObjectiveSharpie.pkg)
// > sharpie bind -output TestFairy -namespace TestFairyLib -sdk iphoneos10.1 TestFairy.h
namespace TestFairyLib
{
	// @interface TestFairy : NSObject
	[BaseType (typeof(NSObject))]
	interface TestFairy
	{
		// +(void)begin:(NSString *)appToken;
		[Static]
		[Export ("begin:")]
		void Begin (string appToken);

		// +(void)begin:(NSString *)appToken withOptions:(NSDictionary *)options;
		[Static]
		[Export ("begin:withOptions:")]
		void Begin (string appToken, NSDictionary options);

		// +(void)setServerEndpoint:(NSString *)serverOverride;
		[Static]
		[Export ("setServerEndpoint:")]
		void SetServerEndpoint (string serverOverride);

		// +(NSString *)version;
		[Static]
		[Export ("version")]
		string Version { get; }

		// +(void)hideView:(UIView *)view;
		[Static]
		[Export ("hideView:")]
		void HideView (UIView view);

		// +(void)hideWebViewElements:(NSString *)selector;
		[Static]
		[Export ("hideWebViewElements:")]
		void HideWebViewElements (string selector);

		// +(void)pushFeedbackController;
		[Static]
		[Export ("pushFeedbackController")]
		void PushFeedbackController ();

		// +(void)sendUserFeedback:(NSString *)feedbackString;
		[Static]
		[Export ("sendUserFeedback:")]
		void SendUserFeedback (string feedbackString);

		// +(void)updateLocation:(NSArray *)locations;
		[Static]
		[Export ("updateLocation:")]
		void UpdateLocation (NSObject[] locations);

		// +(void)checkpoint:(NSString *)name;
		[Static]
		[Export ("checkpoint:")]
		void Checkpoint (string name);

		// +(void)setCorrelationId:(NSString *)correlationId;
		[Static]
		[Export ("setCorrelationId:")]
		void SetCorrelationId (string correlationId);

		// +(void)identify:(NSString *)correlationId;
		[Static]
		[Export ("identify:")]
		void Identify (string correlationId);

		// +(void)identify:(NSString *)correlationId traits:(NSDictionary *)traits;
		[Static]
		[Export ("identify:traits:")]
		void Identify (string correlationId, NSDictionary traits);

		// +(void)pause;
		[Static]
		[Export ("pause")]
		void Pause ();

		// +(void)resume;
		[Static]
		[Export ("resume")]
		void Resume ();

		// +(void)stop;
		[Static]
		[Export ("stop")]
		void Stop ();

		// +(NSString *)sessionUrl;
		[Static]
		[Export ("sessionUrl")]
		string SessionUrl { get; }

		// +(void)takeScreenshot;
		[Static]
		[Export ("takeScreenshot")]
		void TakeScreenshot ();

		// +(void)setScreenName:(NSString *)name;
		[Static]
		[Export ("setScreenName:")]
		void SetScreenName (string name);

		// +(void)setUserId:(NSString *)userId;
		[Static]
		[Export ("setUserId:")]
		void SetUserId (string userId);

		// +(BOOL)setAttribute:(NSString *)key withValue:(NSString *)value;
		[Static]
		[Export ("setAttribute:withValue:")]
		bool SetScreenName (string key, string value);
	}

	[Static]
	partial interface Constants
	{
		// extern NSString *const TFSDKIdentityTraitNameKey;
		[Field ("TFSDKIdentityTraitNameKey", "__Internal")]
		NSString TFSDKIdentityTraitNameKey { get; }

		// extern NSString *const TFSDKIdentityTraitEmailAddressKey;
		[Field ("TFSDKIdentityTraitEmailAddressKey", "__Internal")]
		NSString TFSDKIdentityTraitEmailAddressKey { get; }

		// extern NSString *const TFSDKIdentityTraitBirthdayKey;
		[Field ("TFSDKIdentityTraitBirthdayKey", "__Internal")]
		NSString TFSDKIdentityTraitBirthdayKey { get; }

		// extern NSString *const TFSDKIdentityTraitGenderKey;
		[Field ("TFSDKIdentityTraitGenderKey", "__Internal")]
		NSString TFSDKIdentityTraitGenderKey { get; }

		// extern NSString *const TFSDKIdentityTraitPhoneNumberKey;
		[Field ("TFSDKIdentityTraitPhoneNumberKey", "__Internal")]
		NSString TFSDKIdentityTraitPhoneNumberKey { get; }

		// extern NSString *const TFSDKIdentityTraitWebsiteAddressKey;
		[Field ("TFSDKIdentityTraitWebsiteAddressKey", "__Internal")]
		NSString TFSDKIdentityTraitWebsiteAddressKey { get; }

		// extern NSString *const TFSDKIdentityTraitAgeKey;
		[Field ("TFSDKIdentityTraitAgeKey", "__Internal")]
		NSString TFSDKIdentityTraitAgeKey { get; }

		// extern NSString *const TFSDKIdentityTraitSignupDateKey;
		[Field ("TFSDKIdentityTraitSignupDateKey", "__Internal")]
		NSString TFSDKIdentityTraitSignupDateKey { get; }

		// extern NSString *const TFSDKEnableCrashReporterKey;
		[Field ("TFSDKEnableCrashReporterKey", "__Internal")]
		NSString TFSDKEnableCrashReporterKey { get; }

		// extern NSString *const TestFairyDidShakeDevice;
		[Field ("TestFairyDidShakeDevice", "__Internal")]
		NSString TestFairyDidShakeDevice { get; }

		// extern NSString *const TestFairyWillProvideFeedback;
		[Field ("TestFairyWillProvideFeedback", "__Internal")]
		NSString TestFairyWillProvideFeedback { get; }

		// extern NSString *const TestFairyDidCancelFeedback;
		[Field ("TestFairyDidCancelFeedback", "__Internal")]
		NSString TestFairyDidCancelFeedback { get; }

		// extern NSString *const TestFairyDidSendFeedback;
		[Field ("TestFairyDidSendFeedback", "__Internal")]
		NSString TestFairyDidSendFeedback { get; }
	}
}
