using System;
using System.Runtime.InteropServices;
using Foundation;

// Generated by Objective Sharpie (https://download.xamarin.com/objective-sharpie/ObjectiveSharpie.pkg)
// > sharpie bind -output TestFairy -namespace TestFairyLib -sdk iphoneos10.1 TestFairy.h
namespace TestFairyLib
{
	public static class CFunctions
	{
		// extern void TFLog (NSString *format, ...) __attribute__((format(NSString, 1, 2)));
		[DllImport ("__Internal")]
		public static extern void TFLog (IntPtr format, string arg0);

		// extern void TFLogv (NSString *format, va_list arg_list);
		[DllImport ("__Internal")]
		public static extern unsafe void TFLogv (IntPtr format, sbyte* arg_list);
	}

	public sealed class TFLog
	{
		public static void v(string format, params object[] arg)
		{
			using (var nsFormat = new NSString(string.Format(format, arg)))
			{
				CFunctions.TFLog(nsFormat.Handle, "");
			}
		}
	}
}
