using CoreGraphics;
using CoreAnimation;
using Foundation;
using System;
using System.Drawing;
using TestFairyLib;
using UIKit;

namespace TestFairyIOS
{
	public partial class ViewController : UIViewController
	{
		private UIView box;
		private NSTimer timer;

		private UIView subtitle;
		private UITextView title;
		private UITextView subTitle;

		private float angle = 0;

		static private int BoxStride = 96;

		public ViewController (IntPtr handle) : base (handle)
		{
		}

		private void StartRotationTimer ()
		{
			timer = NSTimer.CreateRepeatingScheduledTimer (0.001, delegate {

				angle += 2.0f;
				if (angle >= 360.0f) {
					angle = 0.0f;
				}

				box.Layer.Transform = CATransform3D.MakeRotation ((float)(angle / 180.0 * Math.PI), 0, 0, 1);
			});
		}

		private void CreateRotatingBox () 
		{
			box = new UIView {
				Frame = new Rectangle ((int)(View.Frame.Width-BoxStride)/2, (int)(View.Frame.Height-BoxStride)/2, BoxStride, BoxStride),
				BackgroundColor = UIColor.Green,
			};

			View.AddSubview (box);
		}

		public override void TouchesMoved (NSSet touches, UIEvent evt)
		{
			base.TouchesMoved (touches, evt);

			UITouch touch = touches.AnyObject as UITouch;
			CGPoint point = touch.LocationInView (View);
			box.Layer.Transform = CATransform3D.Identity;
			box.Frame = new Rectangle ((int)(point.X + BoxStride)/2, (int)(point.Y + BoxStride)/2, BoxStride, BoxStride);
			box.Layer.Transform = CATransform3D.MakeRotation ((float)(angle / 180.0 * Math.PI), 0, 0, 1);
		}

		private void CreateTitle ()
		{
			title = new UITextView {
				Frame = new Rectangle (0, 30, (int)View.Frame.Width, 100),
				TextAlignment = UITextAlignment.Center,
				Font = UIFont.BoldSystemFontOfSize(22),
				Text = "Welcome to TestFairy!",
				TextColor = UIColor.Black,
			};

			subTitle = new UITextView {
				Frame = new Rectangle (0, 75, (int)View.Frame.Width, 100),
				TextAlignment = UITextAlignment.Center,
				Font = UIFont.BoldSystemFontOfSize(22),
				Text = "Shake to provide feedback!",
				TextColor = UIColor.Black,
			};

			View.AddSubview (title);
			View.AddSubview (subTitle);
		}

		private void CreateHiddenSubtitle () 
		{
			// this subtitle will be shown on device or simulator, but won't be in the
			// video generated by testfairy
			subtitle = new UITextView {
				Frame = new Rectangle (0, (int)View.Frame.Height - 48, (int)View.Frame.Width, 48),
				TextAlignment = UITextAlignment.Center,
				Font = UIFont.BoldSystemFontOfSize (12),
				Text = "Secret Text!",
				TextColor = UIColor.Red,
			};

			View.AddSubview (subtitle);

			// pass UIView to TestFairy, let it know to hide this in next frames
			TestFairy.HideView (subtitle);
		}

		#region View lifecycle

		public override void ViewDidLoad ()
		{
			Console.WriteLine ("Made it to ViewDidLoad!");
			Console.WriteLine("Running in thread " + NSThread.Current);

			base.ViewDidLoad ();

			CreateTitle ();
			CreateRotatingBox ();
			CreateHiddenSubtitle ();

			StartRotationTimer ();
		}

		public override void ViewWillUnload ()
		{
			if (timer != null) {
				timer.Invalidate ();
				timer.Dispose ();
				timer = null;
			}
		}
			
		#endregion
	}
}

