name: Build TestFairy for Xamarin 
on: push

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Install MONO Universal
      run: |
        export MONO_VERSION=https://download.mono-project.com/archive/6.8.0/macos-10-universal/MonoFramework-MDK-6.8.0.105.macos10.xamarin.universal.pkg
        wget -O xamarin.universal.pkg -nv "${MONO_VERSION}"
        ls -lsrt xamarin.universal.pkg
        echo "Downloaded xamarin.universal.pkg, installing to /"
        sudo installer -pkg "xamarin.universal.pkg" -target /
    - name: Install MONO for OSX
      run: |
        export XAMARIN_MAC_VERSION=https://dl.xamarin.com/XamarinforMac/Mac/xamarin.mac-2.8.0.58.pkg
        wget -O xamarin.mac.pkg -nv "${XAMARIN_MAC_VERSION}"
        sudo installer -pkg "xamarin.mac.pkg" -target /
    - name: Install MONO for iOS
      run: |
        export XAMARIN_IOS_VERSION=https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-13.14.1.30.pkg
        wget -O xamarin.ios.pkg -nv "${XAMARIN_IOS_VERSION}"
        sudo installer -pkg "xamarin.ios.pkg" -target /
    - name: Install MONO for Android
      run: |
        export XAMARIN_ANDROID_VERSION=https://download.visualstudio.microsoft.com/download/pr/fc059472-448e-4680-a3cd-e3ba032991c2/172ae06981e5555a4113c016179e6f2b/xamarin.android-10.1.3.7.pkg
        wget -O xamarin.android.pkg -nv "${XAMARIN_ANDROID_VERSION}"
        sudo installer -pkg "xamarin.android.pkg" -target /
    - name: Build Xamarin Package
      run: make
    - name: Upload to NuGET
      run: |
        export VERSION=2.0.0
        export MONO=/Library/Frameworks/Mono.framework/Versions/6.8.0/bin/mono
        zip -j9 output/TestFairy.Xamarin-Android.zip output/TestFairy.Android.dll
        zip -j9 output/TestFairy.Xamarin-iOS.zip output/TestFairy.iOS.dll
        sed -i '' -E "s/<version>[^<]+<\/version>/<version>${VERSION}<\/version>/g" nuget/TestFairy.nuspec
        ${MONO} nuget.exe pack nuget/TestFairy.nuspec -BasePath . -OutputDirectory ./output
        ls -lsrt output/TestFairy.Xamarin.nupkg