name: Release TestFairy Xamarin SDK
on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.3.1.app
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=14.10 --android=11.1 --mac=7.4

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build Xamarin Android Package
      run: |
        ANDROID_SDK_VERSION=1.12.12
        curl -s -L https://maven.testfairy.com/com/testfairy/testfairy-android-sdk/${ANDROID_SDK_VERSION}/testfairy-android-sdk-${ANDROID_SDK_VERSION}.aar -o binding/TestFairy.Android/Jars/testfairy-sdk.aar
        mkdir -p output
        msbuild /p:Configuration=Release binding/TestFairy.Android/TestFairy.Android.csproj
        cp binding/TestFairy.Android/bin/Release/TestFairy.Android.dll output/.

    - name: Build Xamarin iOS Package
      run: |
        IOS_VERSION=1.29.2
        curl -s -L https://s3.amazonaws.com/testfairy/sdk/TestFairySDK-${IOS_VERSION}.zip -o  TestFairySDK.zip
        unzip -o -d binding/TestFairy.iOS TestFairySDK.zip TestFairy.h libTestFairy.a
        rm -f TestFairySDK.zip
        mkdir -p output
        msbuild /p:Configuration=Release binding/TestFairy.iOS/TestFairy.iOS.csproj
        cp binding/TestFairy.iOS/bin/Release/TestFairy.iOS.dll output/.

    - name: Add Artifacts to Github Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          output/TestFairy.Xamarin.nupkg
          output/TestFairy.Xamarin-iOS.zip
          output/TestFairy.Xamarin-Android.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to NuGET
      run: |
        echo ${GITHUB_REF##*/} > RELEASE_TAG
        zip -j9 output/TestFairy.Xamarin-Android.zip output/TestFairy.Android.dll
        zip -j9 output/TestFairy.Xamarin-iOS.zip output/TestFairy.iOS.dll
        sed -i '' -E "s/<version>[^<]+<\/version>/<version>$(cat RELEASE_TAG)<\/version>/g" nuget/TestFairy.nuspec
        nuget pack nuget/TestFairy.nuspec -BasePath . -OutputDirectory ./output
        nuget setApiKey ${NUGET_API_KEY} -Source https://www.nuget.org/api/v2/package
        nuget push output/TestFairy.Xamarin.$(cat RELEASE_TAG).nupkg -Source https://www.nuget.org/api/v2/package
        cp output/TestFairy.Xamarin.$(cat RELEASE_TAG).nupkg output/TestFairy.Xamarin.nupkg
      env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

